# Generated by Django 3.0.11 on 2021-01-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('website', '0003_adventureindexpage_adventurepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=255, verbose_name='Name')),
                ('shoe_URL', models.URLField(blank=True, help_text='Link to the model on alfa.no', verbose_name='AlfaModel')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Cupcake Photo')),
            ],
            options={
                'verbose_name': 'Shoes',
                'verbose_name_plural': 'Shoes',
                'ordering': ['shoe_name'],
            },
        ),
    ]
