# Generated by Django 3.0.11 on 2021-01-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_shoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='photo',
            new_name='shoe_photo',
        ),
    ]
