# Generated by Django 3.0.11 on 2021-01-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('website', '0007_auto_20210107_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Adventure Photo'),
        ),
    ]
