# Generated by Django 3.0.11 on 2021-01-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0009_userprofile_verbose_name_plural'),
        ('website', '0008_auto_20210107_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUserProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailusers.UserProfile')),
                ('bio', models.CharField(default='', help_text='Write a bio for your profile page', max_length=40, verbose_name='Bio')),
            ],
            bases=('wagtailusers.userprofile',),
        ),
    ]
