# Generated by Django 3.0.11 on 2021-01-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_extendeduserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduserprofile',
            old_name='bio',
            new_name='test',
        ),
    ]
