# Generated by Django 3.0.11 on 2021-01-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210107_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserprofile',
            name='test',
            field=models.TextField(default='', help_text='Write a bio for your profile page', max_length=40, verbose_name='test'),
        ),
    ]
