# Generated by Django 3.0.11 on 2021-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210108_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduserprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='extendeduserprofile',
            name='body',
        ),
        migrations.RemoveField(
            model_name='extendeduserprofile',
            name='coderedpage_ptr',
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
