# Generated by Django 3.0.11 on 2021-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210108_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuserprofile',
            name='shoes',
            field=models.ManyToManyField(to='website.Shoes'),
        ),
        migrations.AlterField(
            model_name='extuserprofile',
            name='instagram',
            field=models.URLField(default='', help_text='Add your instagram', max_length=255, verbose_name='Instagram url'),
        ),
    ]
