# Generated by Django 3.0.11 on 2021-01-08 18:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20210108_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='content',
            field=wagtail.core.fields.StreamField([('map', wagtail.core.blocks.StructBlock([]))], blank=True, null=True),
        ),
    ]
