# Generated by Django 3.0.11 on 2021-01-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('coderedcms', '0018_auto_20200805_1702'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('website', '0024_auto_20210108_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapPage',
        ),
    ]
