# Generated by Django 3.0.11 on 2021-01-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20210109_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='ankle_stabilization',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='breathability',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='isolation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='sole_stiffness',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='water_resistance',
            field=models.IntegerField(blank=True),
        ),
    ]
