# Generated by Django 3.0.11 on 2021-01-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_profileindexpage_profilepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepage',
            options={'verbose_name': 'Profile page'},
        ),
        migrations.AddField(
            model_name='adventureindexpage',
            name='show_captions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adventureindexpage',
            name='show_images',
            field=models.BooleanField(default=True, verbose_name='Show images'),
        ),
        migrations.AddField(
            model_name='adventureindexpage',
            name='show_meta',
            field=models.BooleanField(default=True, verbose_name='Show author and date info'),
        ),
        migrations.AddField(
            model_name='adventureindexpage',
            name='show_preview_text',
            field=models.BooleanField(default=True, verbose_name='Show preview text'),
        ),
    ]
