# Generated by Django 3.0.11 on 2021-01-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('coderedcms', '0018_auto_20200805_1702'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('website', '0042_auto_20210112_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='coderedpage_ptr',
        ),
        migrations.DeleteModel(
            name='ProfileIndexPage',
        ),
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
