# Generated by Django 3.0.11 on 2021-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20210112_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappage',
            name='show_captions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mappage',
            name='show_images',
            field=models.BooleanField(default=True, verbose_name='Show images'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='show_meta',
            field=models.BooleanField(default=True, verbose_name='Show author and date info'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='show_preview_text',
            field=models.BooleanField(default=True, verbose_name='Show preview text'),
        ),
    ]
