# Generated by Django 3.0.11 on 2021-01-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20210113_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappage',
            name='show_captions',
        ),
        migrations.RemoveField(
            model_name='mappage',
            name='show_images',
        ),
        migrations.RemoveField(
            model_name='mappage',
            name='show_meta',
        ),
        migrations.RemoveField(
            model_name='mappage',
            name='show_preview_text',
        ),
    ]
